### ISSUE TITLE
TypeError: Object of type 'ElementHandle' is not JSON serializable

### ISSUE THREAD

**Issue by michaellucianojr** [rousez/Auto-Amazon-Giveaways#11]
### Run the program twice and run into the same error both times. First time it provided 9 giveaway results before failing; second time it provided 10 giveaway results before failing. 
---------
OSX 10.13.4 

pip3 list
Package    Version  
asyncio    3.4.3    
certifi    2018.4.16
colorama   0.3.9    
numpy      1.14.3   
pip        10.0.1   
pyee       5.0.0    
pyppeteer  0.0.17   
setuptools 39.0.1   
websockets 5.0.1    

-----------------

Traceback (most recent call last):
  File "give_it_away_now.py", line 18, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "give_it_away_now.py", line 16, in main
    await do_ga_workflow(ga_page)
  File "give_it_away_now.py", line 13, in do_ga_workflow
    next_page = await ga_bot.iterate_page(page)
  File "/Users/michaelluciano/Documents/Auto-Amazon-Giveaways-master/lib/giveaway.py", line 151, in iterate_page
    next_page
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyppeteer/page.py", line 803, in evaluate
    return await frame.evaluate(pageFunction, *args, force_expr=force_expr)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyppeteer/frame_manager.py", line 256, in evaluate
    pageFunction, *args, force_expr=force_expr)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyppeteer/execution_context.py", line 37, in evaluate
    pageFunction, *args, force_expr=force_expr)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyppeteer/execution_context.py", line 73, in evaluateHandle
    'awaitPromise': True,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyppeteer/connection.py", line 188, in send
    msg = json.dumps(dict(id=_id, method=method, params=params))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ElementHandle' is not JSON serializable

**Comment by nomisunrider** [comment]
encountered same error.

Traceback (most recent call last):
  File "give_it_away_now.py", line 18, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "give_it_away_now.py", line 16, in main
    await do_ga_workflow(ga_page)
  File "give_it_away_now.py", line 13, in do_ga_workflow
    next_page = await ga_bot.iterate_page(page)
  File "/home/exarkun/Auto-Amazon-Giveaways/lib/giveaway.py", line 151, in iterate_page
    next_page
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/page.py", line 810, in evaluate
    return await frame.evaluate(pageFunction, *args, force_expr=force_expr)
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/frame_manager.py", line 272, in evaluate
    pageFunction, *args, force_expr=force_expr)
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/execution_context.py", line 44, in evaluate
    pageFunction, *args, force_expr=force_expr)
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/execution_context.py", line 80, in evaluateHandle
    'awaitPromise': True,
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/connection.py", line 188, in send
    msg = json.dumps(dict(id=_id, method=method, params=params))
  File "/usr/lib64/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ElementHandle' is not JSON serializable

**Comment by robbiepee** [comment]
encountered same error
