### ISSUE TITLE
TypeError: Object of type 'ElementHandle' is not JSON serializable

### ISSUE THREAD

**Issue by marvic2409** [rousez/Auto-Amazon-Giveaways#13]
I get this issue (Using a Mac) "Traceback (most recent call last):
  File "/Users/User/Downloads/Auto-Amazon-Giveaways-master/give_it_away_now.py", line 18, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/Users/User/Downloads/Auto-Amazon-Giveaways-master/give_it_away_now.py", line 16, in main
    await do_ga_workflow(ga_page)
  File "/Users/User/Downloads/Auto-Amazon-Giveaways-master/give_it_away_now.py", line 13, in do_ga_workflow
    next_page = await ga_bot.iterate_page(page)
  File "/Users/User/Downloads/Auto-Amazon-Giveaways-master/lib/giveaway.py", line 149, in iterate_page
    next_page
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/page.py", line 803, in evaluate
    return await frame.evaluate(pageFunction, *args, force_expr=force_expr)
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/frame_manager.py", line 256, in evaluate
    pageFunction, *args, force_expr=force_expr)
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/execution_context.py", line 37, in evaluate
    pageFunction, *args, force_expr=force_expr)
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/execution_context.py", line 73, in evaluateHandle
    'awaitPromise': True,
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/connection.py", line 188, in send
    msg = json.dumps(dict(id=_id, method=method, params=params))
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)"

**Comment by kogeki** [comment]
same thing happens to me it happens when it tries to move to the next page

**Comment by calvinMartin** [comment]
Hitting the same issue on my windows box.

Traceback (most recent call last):
  File "give_it_away_now.py", line 18, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Python\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "give_it_away_now.py", line 16, in main
    await do_ga_workflow(ga_page)
  File "give_it_away_now.py", line 13, in do_ga_workflow
    next_page = await ga_bot.iterate_page(page)
  File "C:\Python\Auto-Amazon-Giveaways-master\lib\giveaway.py", line 151, in iterate_page
    next_page
  File "C:\Python\lib\site-packages\pyppeteer\page.py", line 810, in evaluate
    return await frame.evaluate(pageFunction, *args, force_expr=force_expr)
  File "C:\Python\lib\site-packages\pyppeteer\frame_manager.py", line 272, in evaluate
    pageFunction, *args, force_expr=force_expr)
  File "C:\Python\lib\site-packages\pyppeteer\execution_context.py", line 44, in evaluate
    pageFunction, *args, force_expr=force_expr)
  File "C:\Python\lib\site-packages\pyppeteer\execution_context.py", line 80, in evaluateHandle
    'awaitPromise': True,
  File "C:\Python\lib\site-packages\pyppeteer\connection.py", line 188, in send
    msg = json.dumps(dict(id=_id, method=method, params=params))
  File "C:\Python\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ElementHandle' is not JSON serializable

**Comment by sniffingpickles** [comment]
@calvinMartin i fixed that issue on my repo:

https://github.com/sniffingpickles/Auto-Amazon-Giveaways
