### ISSUE TITLE
error(log included

### ISSUE THREAD

**Issue by PrayandFlay** [rousez/Auto-Amazon-Giveaways#17]
Traceback (most recent call last):
  File "give_it_away_now.py", line 18, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Users\wwenz\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "give_it_away_now.py", line 16, in main
    await do_ga_workflow(ga_page)
  File "give_it_away_now.py", line 12, in do_ga_workflow
    await ga_bot.process_giveaways(page)
  File "c:\amazong\lib\giveaway.py", line 229, in process_giveaways
    await self.no_req_giveaways()
  File "c:\amazong\lib\giveaway.py", line 158, in no_req_giveaways
    await self.display_ga_result(prize_page)
  File "c:\amazong\lib\giveaway.py", line 103, in display_ga_result
    await prize_page.waitForSelector('.qa-giveaway-result-text')
  File "C:\Users\wwenz\AppData\Local\Programs\Python\Python36\lib\site-packages\pyppeteer\frame_manager.py", line 796, in __await__
    yield from self.promise
pyppeteer.errors.TimeoutError: Waiting failed: timeout 30000ms exceeds.

**Comment by Thaborak** [comment]
Had the same issue

**Comment by sniffingpickles** [comment]
This is because it's getting to the page, and doesn't have an if/else statement for that situation; normally a "giveaway has ended", so just add that to the "check if entered giveaway" function.  Then, if it does it again, do it for the next one.
