### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mastmnds** [rousez/Auto-Amazon-Giveaways#24]
Traceback (most recent call last):
  File "give_it_away_now.py", line 18, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Program Files (x86)\Python37-32\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "give_it_away_now.py", line 16, in main
    await do_ga_workflow(ga_page)
  File "give_it_away_now.py", line 12, in do_ga_workflow
    await ga_bot.process_giveaways(page)
  File "C:\Program Files (x86)\Python37-32\Scripts\Amazon\lib\giveaway.py", line 199, in process_giveaways
    await create_ga_prize(giveaway)
  File "C:\Program Files (x86)\Python37-32\Scripts\Amazon\lib\giveaway.py", line 173, in create_ga_prize
    prize_name_element
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyppeteer\page.py", line 960, in evaluate
    return await frame.evaluate(pageFunction, *args, force_expr=force_expr)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyppeteer\frame_manager.py", line 296, in evaluate
    pageFunction, *args, force_expr=force_expr)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyppeteer\execution_context.py", line 44, in evaluate
    pageFunction, *args, force_expr=force_expr)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyppeteer\execution_context.py", line 87, in evaluateHandle
    helper.getExceptionMessage(exceptionDetails)))
pyppeteer.errors.ElementHandleError: Evaluation failed: TypeError: Cannot read property 'textContent' of null
    at <anonymous>:1:45

**Comment by spankymcfly** [comment]
Same, and error seems transient, doesn't always happen, but happens frequently when launching the script
