### ISSUE TITLE
Script not working at all

### ISSUE THREAD

**Issue by isMunim** [rousez/Auto-Amazon-Giveaways#6]
`Logging into Amazon... Login Successful!  Continuing...

Processing GiveAways for Page: 1

#### Number of 'Tweet a message' Requirement GiveAways found on this page:  7
Traceback (most recent call last):
  File "give_it_away_now.py", line 537, in <module>
    main()
  File "give_it_away_now.py", line 513, in main
    process_tweet_giveaways()
  File "give_it_away_now.py", line 164, in process_tweet_giveaways
    get_url = root_give_away.find_element_by_link_text('View giveaway')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 200, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 518, in find_element
    {"using": by, "value": value})['value']
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"View giveaway"}
  (Session info: chrome=63.0.3239.84)
  (Driver info: chromedriver=2.34.522932 (4140ab217e1ca1bec0c4b4d1b148f3361eb3a03e),platform=Mac OS X 10.13.1 x86_64)`

**Comment by isMunim** [comment]
Refer to this:
https://github.com/zdrouse/Auto-Amazon-Giveaways/issues/2

**Comment by zdrouse** [comment]
Yes, much of the Giveaway pages have changed since I last worked on this project - since this project relies on grabbing HTML elements with Selenium, any changes to that code can break the script. Unfortunately I do not have the time at the moment to fix it.  You can try the fork of this project that is listed there, but I think it is also not fully updated as well.
