### ISSUE TITLE
 Waiting failed: timeout 30000ms exceeds.

### ISSUE THREAD

**Issue by cbjjensen** [rousez/Auto-Amazon-Giveaways#8]
Hi there. Thanks for the project :) .I'm trying to get it up and running, but it seems to hang after going into a giveaway within chromium. Here is the full output:

```
Enter your Amazon email address:  [removed]
Enter your Amazon password:

Processing GiveAway:  Padded Shirt Youth Boys Padded Compression Sports Protective T-Shirt Rib Chest Extreme Exercise, Black, YS
Traceback (most recent call last):
  File "give_it_away_now.py", line 9, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Users\Chad\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "give_it_away_now.py", line 7, in main
    await ga_bot.process_giveaways(ga_page)
  File "O:\GitProjects\Auto-Amazon-Giveaways-master\lib\giveaway.py", line 165, in process_giveaways
    await self.no_req_giveaways()
  File "O:\GitProjects\Auto-Amazon-Giveaways-master\lib\giveaway.py", line 116, in no_req_giveaways
    ga_entry = await self.check_for_entered(prize_page)
  File "O:\GitProjects\Auto-Amazon-Giveaways-master\lib\giveaway.py", line 80, in check_for_entered
    await prize_page.waitForSelector('.qa-giveaway-result-text')
  File "C:\Users\Chad\AppData\Local\Programs\Python\Python36\lib\site-packages\pyppeteer\frame_manager.py", line 678, in __await__
    yield from self.promise
pyppeteer.errors.TimeoutError: Waiting failed: timeout 30000ms exceeds.

```

Here is output to show that requirements have been installed:

```

O:\GitProjects\Auto-Amazon-Giveaways-master>pip install -r requirements.txt
Requirement already satisfied: asyncio in c:\users\chad\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: colorama in c:\users\chad\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: pyppeteer in c:\users\chad\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: pyee in c:\users\chad\appdata\local\programs\python\python36\lib\site-packages (from pyppeteer->-r requirements.txt (line 3))
Requirement already satisfied: websockets in c:\users\chad\appdata\local\programs\python\python36\lib\site-packages (from pyppeteer->-r requirements.txt (line 3))
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

Perhaps I am missing something obvious.

**Comment by Shiratzu** [comment]
i too have the same problem

```
Processing GiveAway:  Dyson V7 Animal Cordless Stick Vacuum Cleaner
Traceback (most recent call last):
  File "give_it_away_now.py", line 9, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "give_it_away_now.py", line 7, in main
    await ga_bot.process_giveaways(ga_page)
  File "/Users/ikyuhmkjiuyiuy/Downloads/Auto-Amazon-Giveaways-master/lib/giveaway.py", line 165, in process_giveaways
    await self.no_req_giveaways()
  File "/Users/ikyuhmkjiuyiuy/Downloads/Auto-Amazon-Giveaways-master/lib/giveaway.py", line 118, in no_req_giveaways
    await prize_page.waitForSelector('#box_click_target')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyppeteer/frame_manager.py", line 678, in __await__
    yield from self.promise
pyppeteer.errors.TimeoutError: Waiting failed: timeout 30000ms exceeds.
```

**Comment by SoleInvictus** [comment]
I had the same issue - more than likely, you either have Amazon's two-step verification activated, or you don't and Amazon is sending you a verification to confirm a new platform anyhow. If either is the case, you'll see the appropriate request pop up in Chromium. Just pause the script, complete the required login, and start it up again.

**Comment by Shiratzu** [comment]
Im not getting any option to log in again. Chromium just stops moving and the script pops up that error

**Comment by Shiratzu** [comment]
I managed to record my screen so I could show what I mean better @_@ https://www.youtube.com/watch?v=vpFIuohdNPM&feature=youtu.be

**Comment by zdrouse** [comment]
@Shiratzu @SoleInvictus 

I've updated the project since I just noticed these issues, can you guys pull the latest commits and try again?

FYI - Page iteration is not working yet.

**Comment by cbjjensen** [comment]
Hi there. I will try and report back with results.

**Comment by cbjjensen** [comment]
Yes, this does appear to have resolve the issue for me! Thanks for the fix 👍

**Comment by chriswayneh** [comment]
@SoleInvictus I'm trying to run the script on a VM, which is working fine, however Amazon is now asking to verify login via typing in whatever is in the image. My question is, how do I pause the script so I can enter in  the info into Chromium and then un-pause the script to continue?

**Comment by sniffingpickles** [comment]
@chriswayneh Best way to do it is to build a small function in the login part that awaits for an element, then asks you input on input prompt.  Do you have an example of when it captcha's you?  Also, are you up to date on chromium?

**Comment by pooponperl** [comment]
... or just disable 2FA for the Chromium login.

**Comment by chriswayneh** [comment]
2FA wasn't enabled. 

To resolve, I opened Chromium, deleted all cookies and manually logged back into Amazon. There was no captcha this time around and everything ran fine after that.

**Comment by Shiratzu** [comment]
@zdrouse yep! other than the page iteration, it's working well, thanks a ton!
